_commit: 0.1.5
_src_path: gh:mapp-metabolomics-unit/mapp-repo-copier-template
common_filename_pattern: '*20250402_PMA_tp24*.mzML'
email: pierre-marie.allard@unifr.ch
gap_filling: true
git_repo_path: /home/allardpm/git_repos/mapp-metabolomics-unit
github_username: commons-teaching
gnps_job_id: ''
ionization_mode: positive
mapp_batch: mapp_batch_00162
mapp_batch_description: Untargeted metabolomics of Arabidopsis thaliana plantlets
    - positive ionisation mode
mapp_project: mapp_project_00050
noise_level: 100000.0
repository_name: group-arabidopsis
target_variable: source_taxon
recorded_setup: true
recorded_repository_name: "group-arabidopsis"
recorded_author: "MAPP Metabolomics Unit"
recorder_email: "pierre-marie.allard@unifr.ch"
recorded_github_username: "commons-teaching"
recorded_mapp_project: "mapp_project_00050"
recorded_mapp_batch: "mapp_batch_00162"


